// Code generated by mockery v2.46.0. DO NOT EDIT.

package usecasesmock

import (
	context "context"

	domain "github.com/guillospy92/crabi/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// UserGetInfoUseCaseInterfaceMock is an autogenerated mock type for the UserGetInfoUseCaseInterface type
type UserGetInfoUseCaseInterfaceMock struct {
	mock.Mock
}

// GetUserInfo provides a mock function with given fields: ctx, email
func (_m *UserGetInfoUseCaseInterfaceMock) GetUserInfo(ctx context.Context, email string) (*domain.UserEntity, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserInfo")
	}

	var r0 *domain.UserEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.UserEntity, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.UserEntity); ok {
		r0 = rf(ctx, email)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.UserEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserGetInfoUseCaseInterfaceMock creates a new instance of UserGetInfoUseCaseInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserGetInfoUseCaseInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserGetInfoUseCaseInterfaceMock {
	mock := &UserGetInfoUseCaseInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
