// Code generated by mockery v2.46.0. DO NOT EDIT.

package usecasesmock

import (
	context "context"

	domain "github.com/guillospy92/crabi/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// UserCreateUseCaseInterfaceMock is an autogenerated mock type for the UserCreateUseCaseInterface type
type UserCreateUseCaseInterfaceMock struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: ctx, user
func (_m *UserCreateUseCaseInterfaceMock) CreateUser(ctx context.Context, user domain.UserEntity) error {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.UserEntity) error); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserCreateUseCaseInterfaceMock creates a new instance of UserCreateUseCaseInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserCreateUseCaseInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserCreateUseCaseInterfaceMock {
	mock := &UserCreateUseCaseInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
